config/routes.rb
Rails.application.routes.draw do
 
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new', as: :new_user_registration
   
  end

  devise_for :users, skip: [:sessions], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'static_pages#home'

  resources :users do
    member do
      get :like_posts
    end
  end

  resources :posts
  resources :comments, only: [:new, :create]
  resources :like_posts, only: [:create, :destroy]
  resources :friendships

  get 'received_request', to: 'friendships#received_request'
  get 'sent_request', to: 'friendships#sent_request'

  get 'search', to: 'users#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_sidebar.html.erb
 <div class="col-2">
  <div class="left-column">
    <ul class="list-group list-group-flush">
      <li class="list-group-item content mb-3 mt-2">
        <%= link_to user_path(current_user) do %>
          <span><%= user_image(current_user, 20) %></span>
          <span><%= name(current_user) %></span>
        <% end %>
      </li>
      <li class="list-group-item content posts">
        <%= link_to posts_path do %>
          <span><%= image_tag("newsfeed.png", :alt => "NewsFeed", :width => '20') %></span> 
          <span>News Feed</span>  
        <% end %>       
      </li>
      <li class="list-group-item subtitle mt-1">
        Explore   
      </li>
      <li class="list-group-item content users">
        <%= link_to users_path do %>
          <span><%= image_tag("find-friend.png", :alt => "Find Friend", :width => '20') %></span> 
          <span>Find Friends</span>    
        <% end %>     
      </li>
      <li class="list-group-item content friendships">
        <%= link_to friendships_path do %>
          <span><%= image_tag("friend-list.png", :alt => "Friend List", :width => '20') %></span> 
          <span>Friend List</span>    
        <% end %>     
      </li>
      <li class="list-group-item content received_request">
        <%= link_to received_request_path do %>
          <span><%= image_tag("group.png", :alt => "Friend Requests", :width => '20') %></span> 
          <span>Friend Requests</span>    
        <% end %>     
      </li>
      <li class="list-group-item content sent_request">
        <%= link_to sent_request_path do %>
          <span><%= image_tag("memories.png", :alt => "Sent Requests", :width => '20') %></span> 
          <span>Sent Requests</span>    
        <% end %>     
      </li>
    </ul>
  </div>
</div>